// <auto-generated />
using Desafio.Infraestrutura.Dados.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Desafio.Infraestrutura.Dados.Migrations
{
    [DbContext(typeof(ContextoBaseDados))]
    partial class ContextoBaseDadosModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sqlPilutiAzure")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Desafio.Dominio.Entidades.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sala")
                        .UseIdentityColumn();

                    b.Property<string>("CodigoSala")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_sala");

                    b.Property<string>("NomeSala")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome_sala");

                    b.Property<int>("OrdemMatriz")
                        .HasColumnType("int")
                        .HasColumnName("ordem_matriz");

                    b.Property<string>("TamanhoSala")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tamanho_sala");

                    b.Property<string>("TipoSala")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_sala");

                    b.HasKey("IdSala");

                    b.ToTable("sala");
                });

            modelBuilder.Entity("Desafio.Dominio.Entidades.TamanhoSala", b =>
                {
                    b.Property<int>("IdTamanhoSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tamanho_sala")
                        .UseIdentityColumn();

                    b.Property<string>("DescricaoTamanhoSala")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao_tamanho_sala");

                    b.HasKey("IdTamanhoSala");

                    b.ToTable("tamanho_sala");
                });

            modelBuilder.Entity("Desafio.Dominio.Entidades.TipoSala", b =>
                {
                    b.Property<int>("IdTipoSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sala")
                        .UseIdentityColumn();

                    b.Property<string>("DescricaoTipoSala")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descricao_tipo_sala");

                    b.HasKey("IdTipoSala");

                    b.ToTable("tipo_sala");
                });
#pragma warning restore 612, 618
        }
    }
}
