FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src

COPY ["Desafio.Apresentacao.WebApi/Desafio.Apresentacao.WebApi.csproj","Desafio.Apresentacao.WebApi/"]
COPY ["Desafio.Aplicacao/Desafio.Aplicacao.csproj","Desafio.Aplicacao/"]
COPY ["Desafio.Dominio/Desafio.Dominio.csproj","Desafio.Dominio/"]
COPY ["Desafio.Infraestrutura.Dados/Desafio.Infraestrutura.Dados.csproj","Desafio.Infraestrutura.Dados/Desafio.Infraestrutura.Dados"]
COPY ["Desafio.Infraestrutura.Migrations/Desafio.Infraestrutura.Migrations.csproj","Desafio.Infraestrutura.Migrations/Desafio.Infraestrutura.Migrations"]
COPY ["Desafio.Apresentacao.WebApi/Desafio.Apresentacao.WebApi.csproj","Desafio.Apresentacao.WebApi/Desafio.Apresentacao"]

RUN dotnet restore "Desafio.Apresentacao.WebApi/Desafio.Apresentacao.WebApi.csproj"

COPY . .

WORKDIR "/src/Desafio.Apresentacao.WebApi"

RUN dotnet build "Desafio.Apresentacao.WebApi.csproj" -c Release -o /app/build




FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS migration
WORKDIR /src
COPY . .
RUN dotnet restore "Desafio.Infraestrutura.Migrations/Desafio.Infraestrutura.Migrations.csproj"
COPY . .
WORKDIR "/src/Desafio.Infraestrutura.Migrations"
RUN dotnet build "Desafio.Infraestrutura.Migrations.csproj" -c Release -o /app/migration

FROM build AS publish
RUN dotnet publish "Desafio.Apresentacao.WebApi.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /migration
COPY --from=migration /app/migration .

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Desafio.Apresentacao.WebApi.dll"]